# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "axa01Us57m/ekVdcdn9fTUCpHErnVMukyUPesKNh0tUYfPit7kv0s2XjU6AJb9Udbi09snuLSEhqPAoOAm2uOsOiZrrqJ5djyUW3hffVQuoEd5ZSidjvkn+apF4GylFpnymh4u4bWKaDqhLwg9998nSk3fB/N/Tygqeq0A1O70qb9SF3R4XW2rVr/PpQnpnr/XGIW/1Y6CC3OPDJH+4VAIKq0yKNPcpstK4ZQQ722ZLodECu2KMzHArhOUFjcYi6aMXDYoqZZaw8z9BVf11hwj7g3DtVtUxk9E8pTC8FSfG0bIUS5h1vCnXr0J2h+4IN5DgO4OVHZ1dXfo4PpGgYa4iDarrbs4rcbT8jg/EadGVy7o3mzBoZgKGzK76qEzOA468iZtZUIGJFwUuV5DKH+GmhI+JEZ5uwd1p4JKAXFXTTFS/6ffpbC+WlPIeQ6a6rRuTaQvztZUGHwpVCyOo6zxaA1YeESNokQvauKj40qfXIHA1EaxJlCUO+zGi0aq4WP07x3CwH/QEQGdW6FAoRYBDIMpxck81rGeduch+UnZbxm92zBA1zHlkR1OqkCRLiZokjGoQQmLzHC4wHkbqL9ARM66or7xmJSjI9ydIZr2NWqv4JcT4BeVCXCjXhPTsVIh7pBgz3l7pfwXsg7+PQcXidRW7zxl2tiksBUp/Znoo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
