travis:
  secure:
    BINSTAR_TOKEN: XL/qa/mwzJdlIq4n4GnwFq+EswaiOXuxLYXxjHBN0cmsPatDUgwaXxpkOShXnVn0T4dYnlW0mbi9nPvGU69QMheZfwM30RufyVP+fZzBQlouQh5VpfIePf46PX0kl2adPodfMfZrjowRgsrKuGY5EBvOplZia0r5Gc3QnesrdQv13aIMjcEeogiXMmQSaRHxTJy8VPRo4rY5BJ3Eyx2DmWnYdHEHpd02ZgcKcwc81H8VL1qoEdD2vqucQZrUadKtTmYXBj9F9IRA5ISipELueCslW125VpP7g1jojkWhk0I42ZwPtuSEeHB8NpcPevwNiIhYXKH3DSXwrzeav+pUcAOcTzCL8n/2pXBTIDgEU/2zN0SRn0VDtumiXkGGQmDKbv/7zcYwp0N8v2sfWbXfRm7JBqPh22RxyYTYZmvarqxc8CW3qokjOzoxUgWPgBAIAYfteUDH6NlNuqeOnmexoul2d01CEoDoZuiyBxiD1gF+h+Yyw26xQnxEpgS+j23CsM5hcUXsK1wSlFZ9pESWaNgj1OFcGpD3sKXB/BWM+VEQue0hQ3Y8t63O1GCtyB+9ie42NXZDmBDml7M7nrDgmdcgkNGzmMbIrngPqiREOFjBEswi74iF3iRtzcHkYcnAGtN9e8g1njKnaUPwVHt23VFn4AL2P+jHce/9e8lS+ZM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
