travis:
  secure:
    BINSTAR_TOKEN: axa01Us57m/ekVdcdn9fTUCpHErnVMukyUPesKNh0tUYfPit7kv0s2XjU6AJb9Udbi09snuLSEhqPAoOAm2uOsOiZrrqJ5djyUW3hffVQuoEd5ZSidjvkn+apF4GylFpnymh4u4bWKaDqhLwg9998nSk3fB/N/Tygqeq0A1O70qb9SF3R4XW2rVr/PpQnpnr/XGIW/1Y6CC3OPDJH+4VAIKq0yKNPcpstK4ZQQ722ZLodECu2KMzHArhOUFjcYi6aMXDYoqZZaw8z9BVf11hwj7g3DtVtUxk9E8pTC8FSfG0bIUS5h1vCnXr0J2h+4IN5DgO4OVHZ1dXfo4PpGgYa4iDarrbs4rcbT8jg/EadGVy7o3mzBoZgKGzK76qEzOA468iZtZUIGJFwUuV5DKH+GmhI+JEZ5uwd1p4JKAXFXTTFS/6ffpbC+WlPIeQ6a6rRuTaQvztZUGHwpVCyOo6zxaA1YeESNokQvauKj40qfXIHA1EaxJlCUO+zGi0aq4WP07x3CwH/QEQGdW6FAoRYBDIMpxck81rGeduch+UnZbxm92zBA1zHlkR1OqkCRLiZokjGoQQmLzHC4wHkbqL9ARM66or7xmJSjI9ydIZr2NWqv4JcT4BeVCXCjXhPTsVIh7pBgz3l7pfwXsg7+PQcXidRW7zxl2tiksBUp/Znoo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
